### ISSUE TITLE
when run example with marathon got error

### ISSUE THREAD

**Issue by pwzgorilla** [paypal/dce-go#22]
I0801 02:42:11.456279  7200 logging.cpp:194] INFO level logging started!
I0801 02:42:11.457401  7200 logging.cpp:199] Logging to /var/log/mesos
I0801 02:42:11.457464  7200 fetcher.cpp:531] Fetcher Info: {"cache_directory":"\/tmp\/mesos\/fetch\/slaves\/dc0144b9-1cbe-49a0-b5ee-096d0b2cbce7-S0","items":[{"action":"BYPASS_CACHE","uri":{"cache":false,"executable":false,"extract":true,"value":"https:\/\/github.com\/mesos\/docker-compose-executor\/releases\/download\/0.1.0\/sample-app.tar.gz"}},{"action":"BYPASS_CACHE","uri":{"cache":false,"executable":false,"extract":false,"value":"http:\/\/192.168.1.64:8090\/config.yaml"}},{"action":"BYPASS_CACHE","uri":{"cache":false,"executable":false,"extract":false,"value":"http:\/\/192.168.1.64:8090\/general.yaml"}},{"action":"BYPASS_CACHE","uri":{"cache":false,"executable":false,"extract":false,"value":"http:\/\/192.168.1.64:8090\/executor"}}],"sandbox_directory":"\/data\/mesos\/slaves\/dc0144b9-1cbe-49a0-b5ee-096d0b2cbce7-S0\/frameworks\/be770577-dded-4778-83cf-b193c2716136-0000\/executors\/marathon-docker-compose-demo.04650ad6-7663-11e7-a1df-024262d6c900\/runs\/290402cb-7668-473b-b485-c49d24edf1f6"}
I0801 02:42:11.464521  7200 fetcher.cpp:442] Fetching URI 'https://github.com/mesos/docker-compose-executor/releases/download/0.1.0/sample-app.tar.gz'
I0801 02:42:11.464573  7200 fetcher.cpp:283] Fetching directly into the sandbox directory
I0801 02:42:11.464634  7200 fetcher.cpp:220] Fetching URI 'https://github.com/mesos/docker-compose-executor/releases/download/0.1.0/sample-app.tar.gz'
I0801 02:42:11.464690  7200 fetcher.cpp:163] Downloading resource from 'https://github.com/mesos/docker-compose-executor/releases/download/0.1.0/sample-app.tar.gz' to '/data/mesos/slaves/dc0144b9-1cbe-49a0-b5ee-096d0b2cbce7-S0/frameworks/be770577-dded-4778-83cf-b193c2716136-0000/executors/marathon-docker-compose-demo.04650ad6-7663-11e7-a1df-024262d6c900/runs/290402cb-7668-473b-b485-c49d24edf1f6/sample-app.tar.gz'
I0801 02:42:13.928701  7200 process.cpp:1246] libprocess is initialized on 172.16.1.17:40272 with 8 worker threads
I0801 02:42:14.029827  7200 fetcher.cpp:121] Extracted '/data/mesos/slaves/dc0144b9-1cbe-49a0-b5ee-096d0b2cbce7-S0/frameworks/be770577-dded-4778-83cf-b193c2716136-0000/executors/marathon-docker-compose-demo.04650ad6-7663-11e7-a1df-024262d6c900/runs/290402cb-7668-473b-b485-c49d24edf1f6/sample-app.tar.gz' into '/data/mesos/slaves/dc0144b9-1cbe-49a0-b5ee-096d0b2cbce7-S0/frameworks/be770577-dded-4778-83cf-b193c2716136-0000/executors/marathon-docker-compose-demo.04650ad6-7663-11e7-a1df-024262d6c900/runs/290402cb-7668-473b-b485-c49d24edf1f6'
I0801 02:42:14.029963  7200 fetcher.cpp:580] Fetched 'https://github.com/mesos/docker-compose-executor/releases/download/0.1.0/sample-app.tar.gz' to '/data/mesos/slaves/dc0144b9-1cbe-49a0-b5ee-096d0b2cbce7-S0/frameworks/be770577-dded-4778-83cf-b193c2716136-0000/executors/marathon-docker-compose-demo.04650ad6-7663-11e7-a1df-024262d6c900/runs/290402cb-7668-473b-b485-c49d24edf1f6/sample-app.tar.gz'
I0801 02:42:14.029992  7200 fetcher.cpp:442] Fetching URI 'http://192.168.1.64:8090/config.yaml'
I0801 02:42:14.030009  7200 fetcher.cpp:283] Fetching directly into the sandbox directory
I0801 02:42:14.030037  7200 fetcher.cpp:220] Fetching URI 'http://192.168.1.64:8090/config.yaml'
I0801 02:42:14.030053  7200 fetcher.cpp:163] Downloading resource from 'http://192.168.1.64:8090/config.yaml' to '/data/mesos/slaves/dc0144b9-1cbe-49a0-b5ee-096d0b2cbce7-S0/frameworks/be770577-dded-4778-83cf-b193c2716136-0000/executors/marathon-docker-compose-demo.04650ad6-7663-11e7-a1df-024262d6c900/runs/290402cb-7668-473b-b485-c49d24edf1f6/config.yaml'
I0801 02:42:14.031924  7200 fetcher.cpp:580] Fetched 'http://192.168.1.64:8090/config.yaml' to '/data/mesos/slaves/dc0144b9-1cbe-49a0-b5ee-096d0b2cbce7-S0/frameworks/be770577-dded-4778-83cf-b193c2716136-0000/executors/marathon-docker-compose-demo.04650ad6-7663-11e7-a1df-024262d6c900/runs/290402cb-7668-473b-b485-c49d24edf1f6/config.yaml'
I0801 02:42:14.031980  7200 fetcher.cpp:442] Fetching URI 'http://192.168.1.64:8090/general.yaml'
I0801 02:42:14.032016  7200 fetcher.cpp:283] Fetching directly into the sandbox directory
I0801 02:42:14.032052  7200 fetcher.cpp:220] Fetching URI 'http://192.168.1.64:8090/general.yaml'
I0801 02:42:14.032075  7200 fetcher.cpp:163] Downloading resource from 'http://192.168.1.64:8090/general.yaml' to '/data/mesos/slaves/dc0144b9-1cbe-49a0-b5ee-096d0b2cbce7-S0/frameworks/be770577-dded-4778-83cf-b193c2716136-0000/executors/marathon-docker-compose-demo.04650ad6-7663-11e7-a1df-024262d6c900/runs/290402cb-7668-473b-b485-c49d24edf1f6/general.yaml'
I0801 02:42:14.048689  7200 fetcher.cpp:580] Fetched 'http://192.168.1.64:8090/general.yaml' to '/data/mesos/slaves/dc0144b9-1cbe-49a0-b5ee-096d0b2cbce7-S0/frameworks/be770577-dded-4778-83cf-b193c2716136-0000/executors/marathon-docker-compose-demo.04650ad6-7663-11e7-a1df-024262d6c900/runs/290402cb-7668-473b-b485-c49d24edf1f6/general.yaml'
I0801 02:42:14.048729  7200 fetcher.cpp:442] Fetching URI 'http://192.168.1.64:8090/executor'
I0801 02:42:14.048740  7200 fetcher.cpp:283] Fetching directly into the sandbox directory
I0801 02:42:14.048763  7200 fetcher.cpp:220] Fetching URI 'http://192.168.1.64:8090/executor'
I0801 02:42:14.048807  7200 fetcher.cpp:163] Downloading resource from 'http://192.168.1.64:8090/executor' to '/data/mesos/slaves/dc0144b9-1cbe-49a0-b5ee-096d0b2cbce7-S0/frameworks/be770577-dded-4778-83cf-b193c2716136-0000/executors/marathon-docker-compose-demo.04650ad6-7663-11e7-a1df-024262d6c900/runs/290402cb-7668-473b-b485-c49d24edf1f6/executor'
I0801 02:42:15.202059  7200 fetcher.cpp:580] Fetched 'http://192.168.1.64:8090/executor' to '/data/mesos/slaves/dc0144b9-1cbe-49a0-b5ee-096d0b2cbce7-S0/frameworks/be770577-dded-4778-83cf-b193c2716136-0000/executors/marathon-docker-compose-demo.04650ad6-7663-11e7-a1df-024262d6c900/runs/290402cb-7668-473b-b485-c49d24edf1f6/executor'
./executor: 1: ./executor: �����: not found
./executor: 9: ./executor: Syntax error: "(" unexpected

**Comment by kkrishna** [comment]
I'd recommend doing vagrant up on [master branch](https://github.com/paypal/dce-go/tree/master)

sample marathon command works in default setup. vagrant setup uses ip "192.168.33.8", while in your log it is 192.168.1.64. there seems to be modification at your end in setup
See below marathon example log (command and response) :

> _LM-SJN-21000951:~ kkrishna$ _**curl -H "Content-Type: application/json" -X POST -d  '{"id": "docker-compose-demo", "cmd": " ", "cpus": 0.5, "mem": 64.0, "ports":[0,0,0], "instances": 1, "executor":"./executor", "labels": { "fileName": "sampleapp/docker-compose.yml,sampleapp/docker-compose-healthcheck.yml" },"uris":["http://192.168.33.8/app.tar.gz","http://192.168.33.8/example/config.yaml","http://192.168.33.8/general.yaml","http://192.168.33.8/executor"]}' http://192.168.33.8:8080/v2/apps**

{"id":"/docker-compose-demo","cmd":" ","args":null,"user":null,"env":{},"instances":1,"cpus":0.5,"mem":64,"disk":0,"executor":"./executor","constraints":[],"uris":["http://192.168.33.8/app.tar.gz","http://192.168.33.8/example/config.yaml","http://192.168.33.8/general.yaml","http://192.168.33.8/executor"],"fetch":[{"uri":"http://192.168.33.8/app.tar.gz","extract":true,"executable":false,"cache":false},{"uri":"http://192.168.33.8/example/config.yaml","extract":false,"executable":false,"cache":false},{"uri":"http://192.168.33.8/general.yaml","extract":false,"executable":false,"cache":false},{"uri":"http://192.168.33.8/executor","extract":false,"executable":false,"cache":false}],"storeUrls":[],"ports":[0,0,0],"portDefinitions":[{"port":0,"protocol":"tcp","labels":{}},{"port":0,"protocol":"tcp","labels":{}},{"port":0,"protocol":"tcp","labels":{}}],"requirePorts":false,"backoffSeconds":1,"backoffFactor":1.15,"maxLaunchDelaySeconds":3600,"container":null,"healthChecks":[],"readinessChecks":[],"dependencies":[],"upgradeStrategy":{"minimumHealthCapacity":1,"maximumOverCapacity":1},"labels":{"fileName":"sampleapp/docker-compose.yml,sampleapp/docker-compose-healthcheck.yml"},"acceptedResourceRoles":null,"ipAddress":null,"version":"2017-08-01T04:16:23.931Z","residency":null,"tasksStaged":0,"tasksRunning":0,"tasksHealthy":0,"tasksUnhealthy":0,"deployments":[{"id":"e16f6a12-b0ae-45bd-929f-44a873e5cfdb"}],"tasks":[]}

 

 

Below mesos sandbox stderr logs for comparison:

> I0801 04:16:40.884155 13593 fetcher.cpp:498] Fetcher Info: {"cache_directory":"\/tmp\/mesos\/fetch\/slaves\/53d82fc6-e90c-4f89-9701-4caa6de24f80-S0\/root","items":[{"action":"BYPASS_CACHE","uri":{"cache":false,"executable":false,"extract":true,"value":"http:\/\/192.168.33.8\/app.tar.gz"}},{"action":"BYPASS_CACHE","uri":{"cache":false,"executable":false,"extract":false,"value":"http:\/\/192.168.33.8\/executor"}},{"action":"BYPASS_CACHE","uri":{"cache":false,"executable":false,"extract":false,"value":"http:\/\/192.168.33.8\/example\/config.yaml"}},{"action":"BYPASS_CACHE","uri":{"cache":false,"executable":false,"extract":false,"value":"http:\/\/192.168.33.8\/general.yaml"}}],"sandbox_directory":"\/var\/lib\/mesos\/slaves\/53d82fc6-e90c-4f89-9701-4caa6de24f80-S0\/frameworks\/53d82fc6-e90c-4f89-9701-4caa6de24f80-0000\/executors\/marathon-docker-compose-demo.38175f68-7670-11e7-b3a2-02428fa58cd1\/runs\/d8932ef8-01f1-4f3e-9f5b-bdfe8a0106e1","user":"root"}
I0801 04:16:40.885723 13593 fetcher.cpp:409] Fetching URI 'http://192.168.33.8/app.tar.gz'
I0801 04:16:40.885736 13593 fetcher.cpp:250] Fetching directly into the sandbox directory
I0801 04:16:40.885749 13593 fetcher.cpp:187] Fetching URI 'http://192.168.33.8/app.tar.gz'
I0801 04:16:40.885757 13593 fetcher.cpp:134] Downloading resource from 'http://192.168.33.8/app.tar.gz' to '/var/lib/mesos/slaves/53d82fc6-e90c-4f89-9701-4caa6de24f80-S0/frameworks/53d82fc6-e90c-4f89-9701-4caa6de24f80-0000/executors/marathon-docker-compose-demo.38175f68-7670-11e7-b3a2-02428fa58cd1/runs/d8932ef8-01f1-4f3e-9f5b-bdfe8a0106e1/app.tar.gz'
I0801 04:16:40.887686 13593 fetcher.cpp:84] Extracting with command: tar -C '/var/lib/mesos/slaves/53d82fc6-e90c-4f89-9701-4caa6de24f80-S0/frameworks/53d82fc6-e90c-4f89-9701-4caa6de24f80-0000/executors/marathon-docker-compose-demo.38175f68-7670-11e7-b3a2-02428fa58cd1/runs/d8932ef8-01f1-4f3e-9f5b-bdfe8a0106e1' -xf '/var/lib/mesos/slaves/53d82fc6-e90c-4f89-9701-4caa6de24f80-S0/frameworks/53d82fc6-e90c-4f89-9701-4caa6de24f80-0000/executors/marathon-docker-compose-demo.38175f68-7670-11e7-b3a2-02428fa58cd1/runs/d8932ef8-01f1-4f3e-9f5b-bdfe8a0106e1/app.tar.gz'
I0801 04:16:40.894608 13593 fetcher.cpp:92] Extracted '/var/lib/mesos/slaves/53d82fc6-e90c-4f89-9701-4caa6de24f80-S0/frameworks/53d82fc6-e90c-4f89-9701-4caa6de24f80-0000/executors/marathon-docker-compose-demo.38175f68-7670-11e7-b3a2-02428fa58cd1/runs/d8932ef8-01f1-4f3e-9f5b-bdfe8a0106e1/app.tar.gz' into '/var/lib/mesos/slaves/53d82fc6-e90c-4f89-9701-4caa6de24f80-S0/frameworks/53d82fc6-e90c-4f89-9701-4caa6de24f80-0000/executors/marathon-docker-compose-demo.38175f68-7670-11e7-b3a2-02428fa58cd1/runs/d8932ef8-01f1-4f3e-9f5b-bdfe8a0106e1'
I0801 04:16:40.894631 13593 fetcher.cpp:547] Fetched 'http://192.168.33.8/app.tar.gz' to '/var/lib/mesos/slaves/53d82fc6-e90c-4f89-9701-4caa6de24f80-S0/frameworks/53d82fc6-e90c-4f89-9701-4caa6de24f80-0000/executors/marathon-docker-compose-demo.38175f68-7670-11e7-b3a2-02428fa58cd1/runs/d8932ef8-01f1-4f3e-9f5b-bdfe8a0106e1/app.tar.gz'
I0801 04:16:40.894636 13593 fetcher.cpp:409] Fetching URI 'http://192.168.33.8/executor'
I0801 04:16:40.894640 13593 fetcher.cpp:250] Fetching directly into the sandbox directory
I0801 04:16:40.894652 13593 fetcher.cpp:187] Fetching URI 'http://192.168.33.8/executor'
I0801 04:16:40.894659 13593 fetcher.cpp:134] Downloading resource from 'http://192.168.33.8/executor' to '/var/lib/mesos/slaves/53d82fc6-e90c-4f89-9701-4caa6de24f80-S0/frameworks/53d82fc6-e90c-4f89-9701-4caa6de24f80-0000/executors/marathon-docker-compose-demo.38175f68-7670-11e7-b3a2-02428fa58cd1/runs/d8932ef8-01f1-4f3e-9f5b-bdfe8a0106e1/executor'
I0801 04:16:40.912859 13593 fetcher.cpp:547] Fetched 'http://192.168.33.8/executor' to '/var/lib/mesos/slaves/53d82fc6-e90c-4f89-9701-4caa6de24f80-S0/frameworks/53d82fc6-e90c-4f89-9701-4caa6de24f80-0000/executors/marathon-docker-compose-demo.38175f68-7670-11e7-b3a2-02428fa58cd1/runs/d8932ef8-01f1-4f3e-9f5b-bdfe8a0106e1/executor'
I0801 04:16:40.912905 13593 fetcher.cpp:409] Fetching URI 'http://192.168.33.8/example/config.yaml'
I0801 04:16:40.912909 13593 fetcher.cpp:250] Fetching directly into the sandbox directory
I0801 04:16:40.912925 13593 fetcher.cpp:187] Fetching URI 'http://192.168.33.8/example/config.yaml'
I0801 04:16:40.912932 13593 fetcher.cpp:134] Downloading resource from 'http://192.168.33.8/example/config.yaml' to '/var/lib/mesos/slaves/53d82fc6-e90c-4f89-9701-4caa6de24f80-S0/frameworks/53d82fc6-e90c-4f89-9701-4caa6de24f80-0000/executors/marathon-docker-compose-demo.38175f68-7670-11e7-b3a2-02428fa58cd1/runs/d8932ef8-01f1-4f3e-9f5b-bdfe8a0106e1/config.yaml'
I0801 04:16:40.913497 13593 fetcher.cpp:547] Fetched 'http://192.168.33.8/example/config.yaml' to '/var/lib/mesos/slaves/53d82fc6-e90c-4f89-9701-4caa6de24f80-S0/frameworks/53d82fc6-e90c-4f89-9701-4caa6de24f80-0000/executors/marathon-docker-compose-demo.38175f68-7670-11e7-b3a2-02428fa58cd1/runs/d8932ef8-01f1-4f3e-9f5b-bdfe8a0106e1/config.yaml'
I0801 04:16:40.913508 13593 fetcher.cpp:409] Fetching URI 'http://192.168.33.8/general.yaml'
I0801 04:16:40.913512 13593 fetcher.cpp:250] Fetching directly into the sandbox directory
I0801 04:16:40.913528 13593 fetcher.cpp:187] Fetching URI 'http://192.168.33.8/general.yaml'
I0801 04:16:40.913533 13593 fetcher.cpp:134] Downloading resource from 'http://192.168.33.8/general.yaml' to '/var/lib/mesos/slaves/53d82fc6-e90c-4f89-9701-4caa6de24f80-S0/frameworks/53d82fc6-e90c-4f89-9701-4caa6de24f80-0000/executors/marathon-docker-compose-demo.38175f68-7670-11e7-b3a2-02428fa58cd1/runs/d8932ef8-01f1-4f3e-9f5b-bdfe8a0106e1/general.yaml'
I0801 04:16:40.913779 13593 fetcher.cpp:547] Fetched 'http://192.168.33.8/general.yaml' to '/var/lib/mesos/slaves/53d82fc6-e90c-4f89-9701-4caa6de24f80-S0/frameworks/53d82fc6-e90c-4f89-9701-4caa6de24f80-0000/executors/marathon-docker-compose-demo.38175f68-7670-11e7-b3a2-02428fa58cd1/runs/d8932ef8-01f1-4f3e-9f5b-bdfe8a0106e1/general.yaml'

Would you try sample marathon command in default vagrant setup and let us know. thanks.

**Comment by JiaminZhu** [comment]
Please make sure you compile executor in vagrant box or linux env.

**Comment by kkrishna** [comment]
Marking this close.
