### ISSUE TITLE
Inconsistent imports for mesos-go

### ISSUE THREAD

**Issue by pradykaushik** [paypal/dce-go#48]
[mesos-go](https://github.com/mesos/mesos-go) updated the directory structure and thus, any library depending on _mesos-go_ must alter the import statements to match the update.

For example,
`github.com/mesos/mesos-go/mesosproto` --> `github.com/mesos/mesos-go/api/v0/mesosproto`
`github.com/mesos/mesos-go/executor` --> `github.com/mesos/mesos-go/api/v0/executor`

**Comment by kkrishna** [comment]
Correct, its an older commit being used. Dependency would be updated in next release.

**Comment by pradykaushik** [comment]
Awesome. Thank you for the quick response.

**Comment by ridv** [comment]
After 3+ plus years, this has finally been addressed here https://github.com/paypal/dce-go/pull/120 Thanks for reporting @pradykaushik
